// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines the payload for granting mailbox authorization to the server.
 */
export type AuthorizeMailboxPayload = { 
/**
 * Ark mailbox identifier scoped to the loaded wallet.
 */
mailbox_id: string, 
/**
 * Authorization expiry as a Unix timestamp in seconds.
 */
expiry: number, 
/**
 * Hex-encoded mailbox authorization.
 */
encoded: string, };
