// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppVersionCheckPayload = { client_version: string, };

export type AppVersionInfo = { minimum_required_version: string, update_required: boolean, };

/**
 * Represents events that can occur during LNURL-auth.
 */
export type AuthEvent = "REGISTERED";

export type AuthPayload = { key: string, sig: string, k1: string, };

export type BackupInfo = { backup_version: number, created_at: string, backup_size: number, };

export type BackupSettingsPayload = { backup_enabled: boolean, };

export type BackupTriggerNotification = { k1: string, };

export type CompleteUploadPayload = { s3_key: string, backup_version: number, backup_size: number, };

export type DefaultSuccessPayload = { success: boolean, };

export type DeleteBackupPayload = { backup_version: number, };

/**
 * Defines device information captured during registration.
 */
export type DeviceInfo = { device_manufacturer: string | null, device_model: string | null, os_name: string | null, os_version: string | null, app_version: string | null, };

export type DownloadUrlResponse = { download_url: string, backup_size: number, };

/**
 * Represents the response for email verification requests.
 */
export type EmailVerificationResponse = { success: boolean, message: string | null, };

export type GetDownloadUrlPayload = { backup_version: number | null, };

export type GetUploadUrlPayload = { backup_version: number, };

export type HeartbeatNotification = { k1: string, notification_id: string, };

export type HeartbeatResponsePayload = { notification_id: string, };

export type LightningInvoiceRequestNotification = { k1: string, transaction_id: string, amount: number, };

export type MaintenanceNotification = { k1: string, };

export type NotificationData = { "notification_type": "maintenance" } & MaintenanceNotification | { "notification_type": "lightning_invoice_request" } & LightningInvoiceRequestNotification | { "notification_type": "backup_trigger" } & BackupTriggerNotification | { "notification_type": "offboarding" } & OffboardingNotification | { "notification_type": "heartbeat" } & HeartbeatNotification;

export type OffboardingNotification = { k1: string, offboarding_request_id: string, address: string, address_signature: string, };

export type RegisterOffboardingRequestPayload = { address: string, address_signature: string, };

export type RegisterOffboardingResponse = { success: boolean, request_id: string, };

/**
 * Defines the payload for a user registration request.
 */
export type RegisterPayload = { 
/**
 * User chosen lightning address
 */
ln_address: string | null, 
/**
 * Optional device information.
 */
device_info: DeviceInfo | null, 
/**
 * Optional Ark address
 */
ark_address: string | null, };

/**
 * Defines the payload for registering a push notification token.
 */
export type RegisterPushToken = { 
/**
 * The Expo push token for the user's device.
 */
push_token: string, };

/**
 * Represents the response for an user registration.
 */
export type RegisterResponse = { 
/**
 * The status of the request, either "OK" or "ERROR".
 */
status: string, 
/**
 * An optional event indicating the outcome of the authentication.
 */
event: AuthEvent | null, 
/**
 * An optional reason for an error, if one occurred.
 */
reason: string | null, 
/**
 * The user's lightning address.
 */
lightning_address: string | null, 
/**
 * Whether the user's email is verified.
 */
is_email_verified: boolean, };

export type ReportJobStatusPayload = { report_type: ReportType, status: ReportStatus, error_message: string | null, };

export type ReportStatus = "success" | "failure";

export type ReportType = "maintenance" | "backup" | "offboarding";

/**
 * Defines the payload for requesting an email verification code.
 */
export type SendEmailVerificationPayload = { email: string, };

/**
 * Defines the payload for submitting a BOLT11 invoice.
 */
export type SubmitInvoicePayload = { 
/**
 * The BOLT11 invoice to be paid.
 */
invoice: string, 
/**
 * The unique identifier for the payment transaction.
 */
transaction_id: string, };

/**
 * Defines the payload for updating a user's lightning address.
 */
export type UpdateLnAddressPayload = { 
/**
 * The new lightning address for the user.
 */
ln_address: string, };

export type UploadUrlResponse = { upload_url: string, s3_key: string, };

/**
 * Defines the payload for verifying an email with a code.
 */
export type VerifyEmailPayload = { code: string, };
